export const clinicImgs = {
  hero: 'https://images.pexels.com/photos/3259629/pexels-photo-3259629.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  mid:  'https://images.pexels.com/photos/305568/pexels-photo-305568.jpeg?auto=compress&cs=tinysrgb&w=800&q=80',
  cta:  'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  gradient: 'from-blue-950/80',
}

export const clinicContent = {
  th: {
    eyebrow: 'คลินิก & ทันตกรรม · ภูเก็ต', h1_main: 'เว็บไซต์คลินิก', h1_sub: 'ที่ผู้ป่วยไว้วางใจ',
    hero_desc: 'เว็บไซต์มืออาชีพสำหรับคลินิกและทันตกรรมในภูเก็ต ภาษาไทยและอังกฤษ จองนัดออนไลน์',
    mid_h2: 'การท่องเที่ยวเชิงการแพทย์กำลังเติบโต',
    mid_p: 'ภูเก็ตเป็นจุดหมายอันดับต้นๆ ของการท่องเที่ยวเชิงการแพทย์ ผู้ป่วยค้นหาคลินิกที่น่าเชื่อถือออนไลน์ เว็บไซต์มืออาชีพคือความประทับใจแรก',
    services: [
      { icon: '📅', label: 'จองนัดออนไลน์', sub: 'ผู้ป่วยจองตรงออนไลน์' },
      { icon: '👨‍⚕️', label: 'โปรไฟล์แพทย์', sub: 'นำเสนอแพทย์และทีมงาน' },
      { icon: '🏥', label: 'บริการทางการแพทย์', sub: 'ภาพรวมการรักษาทั้งหมด' },
      { icon: '🌍', label: 'SEO ทางการแพทย์', sub: 'พบได้โดยผู้ป่วยนานาชาติ' },
      { icon: '🔒', label: 'ความน่าเชื่อถือ', sub: 'แสดงใบรับรองและการรับรอง' },
      { icon: '📋', label: 'แบบฟอร์มผู้ป่วย', sub: 'แบบฟอร์มออนไลน์ก่อนเข้ารับบริการ' },
      { icon: '💊', label: 'ความเชี่ยวชาญ', sub: 'ความเชี่ยวชาญทางการแพทย์' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'ติดต่อตรงกับคลินิก' },
    ],
    packages: [
      { name: 'หน้าเดียว', price: '฿25,000', eur: '~€640', features: ['ภาพรวมบริการ','ไทย & อังกฤษ','จองนัด','ติดต่อ LINE'], highlight: false },
      { name: 'ธุรกิจ', price: '฿45,000', eur: '~€1,150', features: ['จองออนไลน์','โปรไฟล์แพทย์','SEO การแพทย์','รีวิว'], highlight: true },
      { name: 'พรีเมียม', price: '฿65,000', eur: '~€1,660', features: ['พอร์ทัลผู้ป่วย','แบบฟอร์มออนไลน์','หลายภาษา','SEO เต็มรูปแบบ'], highlight: false },
    ],
  },
  en: {
    eyebrow: 'Clinic & Dental · Medical · Phuket', h1_main: 'Website for your clinic', h1_sub: 'Trust that brings patients',
    hero_desc: 'Professional website for clinics and dental practices in Phuket. Thai & English. Online appointments.',
    mid_h2: 'Medical tourism is growing',
    mid_p: 'Phuket is a top destination for medical tourism. Patients search online for clinics they trust. A professional website is your first impression.',
    services: [
      { icon: '📅', label: 'Online appointments', sub: 'Patients book directly online' },
      { icon: '👨‍⚕️', label: 'Doctor profiles', sub: 'Doctor & staff presentation' },
      { icon: '🏥', label: 'Medical services', sub: 'Full treatment overview' },
      { icon: '🌍', label: 'Medical SEO', sub: 'Found by international patients' },
      { icon: '🔒', label: 'Trust signals', sub: 'Certificates & accreditations' },
      { icon: '📋', label: 'Patient forms', sub: 'Online intake forms' },
      { icon: '💊', label: 'Specialisations', sub: 'Your medical specialisations' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct contact with the practice' },
    ],
    packages: [
      { name: 'One-Page', price: '฿25,000', eur: '~€640', features: ['Services overview','Thai & English','Appointments','LINE contact'], highlight: false },
      { name: 'Business', price: '฿45,000', eur: '~€1,150', features: ['Online booking','Doctor profiles','Medical SEO','Reviews'], highlight: true },
      { name: 'Premium', price: '฿65,000', eur: '~€1,660', features: ['Patient portal','Online forms','Multilingual','Full SEO'], highlight: false },
    ],
  },
  nl: {
    eyebrow: 'Kliniek & Tandarts · Medical · Phuket', h1_main: 'Website voor uw kliniek', h1_sub: 'Vertrouwen wekt patiënten',
    hero_desc: 'Professionele website voor klinieken en tandartspraktijken in Phuket. Thai & Engels. Online afspraken.',
    mid_h2: 'Medisch toerisme groeit',
    mid_p: 'Phuket is een topbestemming voor medisch toerisme. Patiënten zoeken online naar klinieken die ze vertrouwen. Een professionele website is uw visitekaartje.',
    services: [
      { icon: '📅', label: 'Online afspraken', sub: 'Patiënten boeken direct online' },
      { icon: '👨‍⚕️', label: 'Doktersprofielen', sub: 'Arts & staf presentatie' },
      { icon: '🏥', label: 'Medische diensten', sub: 'Volledig overzicht behandelingen' },
      { icon: '🌍', label: 'Medische SEO', sub: 'Gevonden door internationale patiënten' },
      { icon: '🔒', label: 'Vertrouwen', sub: 'Certificaten & accreditaties tonen' },
      { icon: '📋', label: 'Patiëntformulieren', sub: 'Online intake formulieren' },
      { icon: '💊', label: 'Specialisaties', sub: 'Uw medische specialisaties' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct contact met de praktijk' },
    ],
    packages: [
      { name: 'One-Page', price: '฿25,000', eur: '~€640', features: ['Diensten overzicht','Thai & Engels','Afspraken','LINE contact'], highlight: false },
      { name: 'Business', price: '฿45,000', eur: '~€1,150', features: ['Online boekingen','Doktersprofielen','Medische SEO','Reviews'], highlight: true },
      { name: 'Premium', price: '฿65,000', eur: '~€1,660', features: ['Patiëntportaal','Formulieren','Meertalig','Volledige SEO'], highlight: false },
    ],
  },
  ru: {
    eyebrow: 'Клиника & Стоматология · Пхукет', h1_main: 'Сайт для клиники', h1_sub: 'Которому доверяют пациенты',
    hero_desc: 'Профессиональный сайт для клиник и стоматологий Пхукета. Тайский и английский. Онлайн-запись.',
    mid_h2: 'Медицинский туризм растёт',
    mid_p: 'Пхукет — топ-направление для медицинского туризма. Пациенты ищут клиники онлайн. Профессиональный сайт — ваше первое впечатление.',
    services: [
      { icon: '📅', label: 'Онлайн-запись', sub: 'Пациенты записываются напрямую' },
      { icon: '👨‍⚕️', label: 'Профили врачей', sub: 'Презентация врачей и персонала' },
      { icon: '🏥', label: 'Медицинские услуги', sub: 'Полный обзор лечения' },
      { icon: '🌍', label: 'Медицинский SEO', sub: 'Найден международными пациентами' },
      { icon: '🔒', label: 'Доверие', sub: 'Сертификаты и аккредитации' },
      { icon: '📋', label: 'Формы пациентов', sub: 'Онлайн-анкеты' },
      { icon: '💊', label: 'Специализации', sub: 'Ваши медицинские специализации' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Прямой контакт с клиникой' },
    ],
    packages: [
      { name: 'Одна страница', price: '฿25,000', eur: '~€640', features: ['Обзор услуг','Тайский & Английский','Запись','Контакт LINE'], highlight: false },
      { name: 'Бизнес', price: '฿45,000', eur: '~€1,150', features: ['Онлайн-запись','Профили врачей','Мед. SEO','Отзывы'], highlight: true },
      { name: 'Премиум', price: '฿65,000', eur: '~€1,660', features: ['Портал пациентов','Онлайн-формы','Многоязычный','Полный SEO'], highlight: false },
    ],
  },
  de: {
    eyebrow: 'Klinik & Zahnarzt · Medizin · Phuket', h1_main: 'Website für Ihre Klinik', h1_sub: 'Vertrauen, das Patienten bringt',
    hero_desc: 'Professionelle Website für Kliniken und Zahnarztpraxen in Phuket. Thai & Englisch. Online-Termine.',
    mid_h2: 'Medizintourismus wächst',
    mid_p: 'Phuket ist ein Top-Ziel für Medizintourismus. Patienten suchen online nach vertrauenswürdigen Kliniken. Eine professionelle Website ist Ihr erster Eindruck.',
    services: [
      { icon: '📅', label: 'Online-Termine', sub: 'Patienten buchen direkt online' },
      { icon: '👨‍⚕️', label: 'Arztprofile', sub: 'Arzt- & Mitarbeiterpräsentation' },
      { icon: '🏥', label: 'Medizinische Leistungen', sub: 'Vollständige Behandlungsübersicht' },
      { icon: '🌍', label: 'Medizinisches SEO', sub: 'Von internationalen Patienten gefunden' },
      { icon: '🔒', label: 'Vertrauenssignale', sub: 'Zertifikate & Akkreditierungen' },
      { icon: '📋', label: 'Patientenformulare', sub: 'Online-Aufnahmeformulare' },
      { icon: '💊', label: 'Spezialisierungen', sub: 'Ihre medizinischen Spezialisierungen' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direktkontakt mit der Praxis' },
    ],
    packages: [
      { name: 'One-Pager', price: '฿25,000', eur: '~€640', features: ['Leistungsübersicht','Thai & Englisch','Termine','LINE Kontakt'], highlight: false },
      { name: 'Business', price: '฿45,000', eur: '~€1,150', features: ['Online-Buchung','Arztprofile','Med. SEO','Bewertungen'], highlight: true },
      { name: 'Premium', price: '฿65,000', eur: '~€1,660', features: ['Patientenportal','Online-Formulare','Mehrsprachig','Vollst. SEO'], highlight: false },
    ],
  },
}
