export const restaurantImgs = {
  hero: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  mid:  'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800&q=80',
  cta:  'https://images.pexels.com/photos/67468/pexels-photo-67468.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  gradient: 'from-orange-950/80',
}

export const restaurantContent = {
  th: {
    eyebrow: 'ร้านอาหาร · ภูเก็ต', h1_main: 'เว็บไซต์ร้านอาหาร', h1_sub: 'เต็มไปด้วยลูกค้า',
    hero_desc: 'เมนูออนไลน์ จองโต๊ะ และ Google Maps พบได้ทั้งนักท่องเที่ยวและคนท้องถิ่นในภูเก็ต',
    mid_h2: 'นักท่องเที่ยวค้นหาออนไลน์',
    mid_p: 'ในปี 2025 กว่า 90% ของนักท่องเที่ยวในภูเก็ตค้นหาร้านอาหารออนไลน์ ไม่มีเว็บไซต์? พวกเขาไปร้านข้างๆ',
    services: [
      { icon: '🍽️', label: 'เมนูออนไลน์', sub: 'เมนูไทยและอังกฤษพร้อมรูปภาพ' },
      { icon: '📅', label: 'จองโต๊ะออนไลน์', sub: 'รับจองโต๊ะผ่านเว็บไซต์' },
      { icon: '📍', label: 'Google Maps & SEO', sub: 'พบได้ทั้งนักท่องเที่ยวและคนท้องถิ่น' },
      { icon: '⭐', label: 'รีวิว', sub: 'รีวิว Google สดบนเว็บไซต์' },
      { icon: '📸', label: 'แกลเลอรีภาพ', sub: 'อาหาร บรรยากาศ และสถานที่' },
      { icon: '🌍', label: 'หลายภาษา', sub: 'ไทย อังกฤษ รัสเซีย และอื่นๆ' },
      { icon: '💳', label: 'ชำระเงินออนไลน์', sub: 'QR code และการชำระออนไลน์' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'ติดต่อตรงและจองโต๊ะ' },
    ],
    packages: [
      { name: 'หน้าเดียว', price: '฿20,000', eur: '~€500', features: ['เมนูออนไลน์','ไทย & อังกฤษ','Google Maps','ปุ่ม LINE'], highlight: false },
      { name: 'ธุรกิจ', price: '฿35,000', eur: '~€900', features: ['จองโต๊ะ','แกลเลอรีภาพ','รีวิว','Local SEO'], highlight: true },
      { name: 'พรีเมียม', price: '฿55,000', eur: '~€1,400', features: ['หลายภาษา','ชำระออนไลน์','SEO เต็มรูปแบบ','ออกแบบพิเศษ'], highlight: false },
    ],
  },
  en: {
    eyebrow: 'Restaurant & Food · Phuket', h1_main: 'Website for your restaurant', h1_sub: 'Full of guests',
    hero_desc: 'Online menu, reservations & Google Maps. Found by tourists and locals in Phuket.',
    mid_h2: 'Tourists search online',
    mid_p: 'In 2025, over 90% of tourists in Phuket search online for restaurants. No website? They go next door.',
    services: [
      { icon: '🍽️', label: 'Online menu', sub: 'Menu in Thai & English with photos' },
      { icon: '📅', label: 'Reservations', sub: 'Online table reservations' },
      { icon: '📍', label: 'Google Maps & SEO', sub: 'Found by tourists & locals' },
      { icon: '⭐', label: 'Reviews', sub: 'Google Reviews live on your site' },
      { icon: '📸', label: 'Photo gallery', sub: 'Food, atmosphere & location photos' },
      { icon: '🌍', label: 'Multilingual', sub: 'Thai, English, Russian & more' },
      { icon: '💳', label: 'Online payments', sub: 'QR code & online payments' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct contact & reservations' },
    ],
    packages: [
      { name: 'One-Page', price: '฿20,000', eur: '~€500', features: ['Online menu','Thai & English','Google Maps','LINE button'], highlight: false },
      { name: 'Business', price: '฿35,000', eur: '~€900', features: ['Reservations','Photo gallery','Reviews','Local SEO'], highlight: true },
      { name: 'Premium', price: '฿55,000', eur: '~€1,400', features: ['Multilingual','Online payments','Full SEO','Custom design'], highlight: false },
    ],
  },
  nl: {
    eyebrow: 'Restaurant & Horeca · Phuket', h1_main: 'Website voor uw restaurant', h1_sub: 'Vol met gasten',
    hero_desc: 'Online menu, reserveringen en Google Maps. Gevonden door toeristen én locals in Phuket.',
    mid_h2: 'Toeristen zoeken online',
    mid_p: "In 2025 zoekt meer dan 90% van toeristen in Phuket online naar restaurants. Geen website? Ze gaan naar de buren.",
    services: [
      { icon: '🍽️', label: 'Online menu', sub: "Menu in Thai & Engels met foto's" },
      { icon: '📅', label: 'Reserveringen', sub: 'Online tafelreserveringen' },
      { icon: '📍', label: 'Google Maps & SEO', sub: 'Gevonden door toeristen & locals' },
      { icon: '⭐', label: 'Reviews', sub: 'Google Reviews live op je site' },
      { icon: '📸', label: 'Fotogallerij', sub: "Eten, sfeer & locatie foto's" },
      { icon: '🌍', label: 'Meertalig', sub: 'Thai, Engels, Russisch & meer' },
      { icon: '💳', label: 'Online betalen', sub: 'QR code & online betalingen' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct contact & reserveringen' },
    ],
    packages: [
      { name: 'One-Page', price: '฿20,000', eur: '~€500', features: ['Online menu','Thai & Engels','Google Maps','LINE knop'], highlight: false },
      { name: 'Business', price: '฿35,000', eur: '~€900', features: ['Reserveringen','Fotogallerij','Reviews','Local SEO'], highlight: true },
      { name: 'Premium', price: '฿55,000', eur: '~€1,400', features: ['Meertalig','Online betalen','Volledige SEO','Maatwerk'], highlight: false },
    ],
  },
  ru: {
    eyebrow: 'Ресторан · Пхукет', h1_main: 'Сайт для ресторана', h1_sub: 'Полный гостей',
    hero_desc: 'Онлайн-меню, бронирование и Google Maps. Находят туристы и местные жители Пхукета.',
    mid_h2: 'Туристы ищут онлайн',
    mid_p: 'В 2025 году более 90% туристов на Пхукете ищут рестораны в интернете. Нет сайта? Они идут к соседям.',
    services: [
      { icon: '🍽️', label: 'Онлайн-меню', sub: 'Меню на тайском и английском с фото' },
      { icon: '📅', label: 'Бронирование столиков', sub: 'Онлайн-резервация через сайт' },
      { icon: '📍', label: 'Google Maps & SEO', sub: 'Находят туристы и местные' },
      { icon: '⭐', label: 'Отзывы', sub: 'Живые отзывы Google на сайте' },
      { icon: '📸', label: 'Фотогалерея', sub: 'Еда, атмосфера и интерьер' },
      { icon: '🌍', label: 'Многоязычный', sub: 'Тайский, английский, русский и др.' },
      { icon: '💳', label: 'Онлайн-оплата', sub: 'QR-код и онлайн-платежи' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Прямой контакт и бронирование' },
    ],
    packages: [
      { name: 'Одна страница', price: '฿20,000', eur: '~€500', features: ['Онлайн-меню','Тайский & Английский','Google Maps','Кнопка LINE'], highlight: false },
      { name: 'Бизнес', price: '฿35,000', eur: '~€900', features: ['Бронирование','Фотогалерея','Отзывы','Local SEO'], highlight: true },
      { name: 'Премиум', price: '฿55,000', eur: '~€1,400', features: ['Многоязычный','Онлайн-оплата','Полный SEO','Индивид. дизайн'], highlight: false },
    ],
  },
  de: {
    eyebrow: 'Restaurant & Gastronomie · Phuket', h1_main: 'Website für Ihr Restaurant', h1_sub: 'Voll mit Gästen',
    hero_desc: 'Online-Menü, Reservierungen und Google Maps. Von Touristen und Einheimischen in Phuket gefunden.',
    mid_h2: 'Touristen suchen online',
    mid_p: '2025 suchen über 90% der Touristen in Phuket online nach Restaurants. Keine Website? Sie gehen nebenan.',
    services: [
      { icon: '🍽️', label: 'Online-Menü', sub: 'Menü auf Thai & Englisch mit Fotos' },
      { icon: '📅', label: 'Reservierungen', sub: 'Online-Tischreservierungen' },
      { icon: '📍', label: 'Google Maps & SEO', sub: 'Von Touristen & Einheimischen gefunden' },
      { icon: '⭐', label: 'Bewertungen', sub: 'Live Google-Bewertungen auf Ihrer Website' },
      { icon: '📸', label: 'Fotogalerie', sub: 'Essen, Atmosphäre & Location' },
      { icon: '🌍', label: 'Mehrsprachig', sub: 'Thai, Englisch, Russisch & mehr' },
      { icon: '💳', label: 'Online-Zahlung', sub: 'QR-Code & Online-Zahlungen' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direktkontakt & Reservierungen' },
    ],
    packages: [
      { name: 'One-Pager', price: '฿20,000', eur: '~€500', features: ['Online-Menü','Thai & Englisch','Google Maps','LINE-Button'], highlight: false },
      { name: 'Business', price: '฿35,000', eur: '~€900', features: ['Reservierungen','Fotogalerie','Bewertungen','Local SEO'], highlight: true },
      { name: 'Premium', price: '฿55,000', eur: '~€1,400', features: ['Mehrsprachig','Online-Zahlung','Vollst. SEO','Individ. Design'], highlight: false },
    ],
  },
}
