export const schoolImgs = {
  hero: 'https://images.pexels.com/photos/8466984/pexels-photo-8466984.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  mid:  'https://images.pexels.com/photos/5905700/pexels-photo-5905700.jpeg?auto=compress&cs=tinysrgb&w=800&q=80',
  cta:  'https://images.pexels.com/photos/8535236/pexels-photo-8535236.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  gradient: 'from-purple-950/80',
}

export const schoolContent = {
  th: {
    eyebrow: 'โรงเรียน & สถาบันภาษา · ภูเก็ต', h1_main: 'เว็บไซต์โรงเรียน', h1_sub: 'ดึงดูดนักเรียนใหม่',
    hero_desc: 'เว็บไซต์มืออาชีพสำหรับโรงเรียนและสถาบันภาษาในภูเก็ต สมัครเรียนออนไลน์ ภาษาไทยและอังกฤษ',
    mid_h2: 'ผู้ปกครองค้นหาออนไลน์',
    mid_p: 'ผู้ปกครองในภูเก็ตค้นหาโรงเรียนออนไลน์ เว็บไซต์มืออาชีพพร้อมหลักสูตร ครูผู้สอน และแบบฟอร์มสมัครเรียนเป็นสิ่งจำเป็น',
    services: [
      { icon: '📝', label: 'สมัครเรียนออนไลน์', sub: 'นักเรียนสมัครตรงออนไลน์' },
      { icon: '📚', label: 'หลักสูตรและตารางเรียน', sub: 'ภาพรวมวิชาและตารางเรียน' },
      { icon: '👨‍🏫', label: 'โปรไฟล์ครูผู้สอน', sub: 'นำเสนอครูและทีมงาน' },
      { icon: '🌍', label: 'หลายภาษา', sub: 'ไทย & อังกฤษสำหรับผู้ปกครองทุกคน' },
      { icon: '📸', label: 'แกลเลอรีกิจกรรม', sub: 'รูปภาพกิจกรรมและอีเวนต์' },
      { icon: '📅', label: 'ปฏิทินโรงเรียน', sub: 'วันหยุดและกำหนดการ' },
      { icon: '🏆', label: 'ผลสัมฤทธิ์', sub: 'แสดงผลการเรียนและรางวัล' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'ติดต่อตรงกับโรงเรียน' },
    ],
    packages: [
      { name: 'หน้าเดียว', price: '฿22,000', eur: '~€560', features: ['ข้อมูลโรงเรียน','ไทย & อังกฤษ','แบบฟอร์มติดต่อ','ปุ่ม LINE'], highlight: false },
      { name: 'ธุรกิจ', price: '฿38,000', eur: '~€970', features: ['สมัครออนไลน์','โปรไฟล์ครู','แกลเลอรี','SEO'], highlight: true },
      { name: 'พรีเมียม', price: '฿58,000', eur: '~€1,480', features: ['พอร์ทัลนักเรียน','ระบบปฏิทิน','หลายภาษา','SEO เต็มรูปแบบ'], highlight: false },
    ],
  },
  en: {
    eyebrow: 'School & Language Institute · Phuket', h1_main: 'Website for your school', h1_sub: 'Attract more students',
    hero_desc: 'Professional website for schools and language institutes in Phuket. Online enrolment. Thai & English.',
    mid_h2: 'Parents search online',
    mid_p: 'Parents in Phuket search online for schools for their children. A professional website with curriculum, teachers and enrolment form is essential.',
    services: [
      { icon: '📝', label: 'Online enrolment', sub: 'Students enrol directly online' },
      { icon: '📚', label: 'Curriculum', sub: 'Timetable & subjects overview' },
      { icon: '👨‍🏫', label: 'Teacher profiles', sub: 'Teachers & staff presentation' },
      { icon: '🌍', label: 'Multilingual', sub: 'Thai & English for all parents' },
      { icon: '📸', label: 'Activity gallery', sub: 'Photos of activities & events' },
      { icon: '📅', label: 'School calendar', sub: 'Holidays & events calendar' },
      { icon: '🏆', label: 'Achievements', sub: 'Results & distinctions display' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct contact with the school' },
    ],
    packages: [
      { name: 'One-Page', price: '฿22,000', eur: '~€560', features: ['School info','Thai & English','Contact form','LINE button'], highlight: false },
      { name: 'Business', price: '฿38,000', eur: '~€970', features: ['Online enrolment','Teacher profiles','Gallery','SEO'], highlight: true },
      { name: 'Premium', price: '฿58,000', eur: '~€1,480', features: ['Student portal','Calendar system','Multilingual','Full SEO'], highlight: false },
    ],
  },
  nl: {
    eyebrow: 'School & Taalinstituut · Phuket', h1_main: 'Website voor uw school', h1_sub: 'Meer leerlingen aantrekken',
    hero_desc: 'Professionele website voor scholen en taalinstituten in Phuket. Online inschrijving. Thai & Engels.',
    mid_h2: 'Ouders zoeken online',
    mid_p: 'Ouders in Phuket zoeken online naar scholen voor hun kinderen. Een professionele website met curriculum, leraren en inschrijfformulier is essentieel.',
    services: [
      { icon: '📝', label: 'Online inschrijving', sub: 'Leerlingen schrijven zich direct in' },
      { icon: '📚', label: 'Curriculum', sub: 'Lesrooster & vakken overzicht' },
      { icon: '👨‍🏫', label: 'Leraarprofielen', sub: 'Leraren & staf presentatie' },
      { icon: '🌍', label: 'Meertalig', sub: 'Thai & Engels voor alle ouders' },
      { icon: '📸', label: 'Activiteiten gallerij', sub: "Foto's van activiteiten & events" },
      { icon: '📅', label: 'Schoolkalender', sub: 'Vakantiedagen & evenementen' },
      { icon: '🏆', label: 'Prestaties', sub: 'Resultaten & onderscheidingen' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct contact met de school' },
    ],
    packages: [
      { name: 'One-Page', price: '฿22,000', eur: '~€560', features: ['School info','Thai & Engels','Contact formulier','LINE knop'], highlight: false },
      { name: 'Business', price: '฿38,000', eur: '~€970', features: ['Online inschrijving','Leraarprofielen','Gallerij','SEO'], highlight: true },
      { name: 'Premium', price: '฿58,000', eur: '~€1,480', features: ['Leerlingportaal','Kalender systeem','Meertalig','Volledige SEO'], highlight: false },
    ],
  },
  ru: {
    eyebrow: 'Школа & Языковой институт · Пхукет', h1_main: 'Сайт для школы', h1_sub: 'Привлекайте больше учеников',
    hero_desc: 'Профессиональный сайт для школ и языковых институтов Пхукета. Онлайн-запись. Тайский и английский.',
    mid_h2: 'Родители ищут онлайн',
    mid_p: 'Родители на Пхукете ищут школы для детей онлайн. Профессиональный сайт с программой, учителями и формой записи необходим.',
    services: [
      { icon: '📝', label: 'Онлайн-запись', sub: 'Ученики записываются напрямую' },
      { icon: '📚', label: 'Учебная программа', sub: 'Расписание и предметы' },
      { icon: '👨‍🏫', label: 'Профили учителей', sub: 'Презентация учителей и персонала' },
      { icon: '🌍', label: 'Многоязычный', sub: 'Тайский и английский для родителей' },
      { icon: '📸', label: 'Галерея мероприятий', sub: 'Фото мероприятий и событий' },
      { icon: '📅', label: 'Школьный календарь', sub: 'Каникулы и расписание событий' },
      { icon: '🏆', label: 'Достижения', sub: 'Результаты и награды' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Прямой контакт со школой' },
    ],
    packages: [
      { name: 'Одна страница', price: '฿22,000', eur: '~€560', features: ['Инфо о школе','Тайский & Английский','Форма контакта','Кнопка LINE'], highlight: false },
      { name: 'Бизнес', price: '฿38,000', eur: '~€970', features: ['Онлайн-запись','Профили учителей','Галерея','SEO'], highlight: true },
      { name: 'Премиум', price: '฿58,000', eur: '~€1,480', features: ['Портал ученика','Система календаря','Многоязычный','Полный SEO'], highlight: false },
    ],
  },
  de: {
    eyebrow: 'Schule & Sprachinstitut · Phuket', h1_main: 'Website für Ihre Schule', h1_sub: 'Mehr Schüler gewinnen',
    hero_desc: 'Professionelle Website für Schulen und Sprachinstitute in Phuket. Online-Anmeldung. Thai & Englisch.',
    mid_h2: 'Eltern suchen online',
    mid_p: 'Eltern in Phuket suchen online nach Schulen für ihre Kinder. Eine professionelle Website mit Lehrplan, Lehrern und Anmeldeformular ist unerlässlich.',
    services: [
      { icon: '📝', label: 'Online-Anmeldung', sub: 'Schüler melden sich direkt an' },
      { icon: '📚', label: 'Lehrplan', sub: 'Stundenplan & Fächerübersicht' },
      { icon: '👨‍🏫', label: 'Lehrerprofile', sub: 'Lehrer- & Mitarbeiterpräsentation' },
      { icon: '🌍', label: 'Mehrsprachig', sub: 'Thai & Englisch für alle Eltern' },
      { icon: '📸', label: 'Aktivitätengalerie', sub: 'Fotos von Aktivitäten & Events' },
      { icon: '📅', label: 'Schulkalender', sub: 'Ferien & Veranstaltungskalender' },
      { icon: '🏆', label: 'Leistungen', sub: 'Ergebnisse & Auszeichnungen' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direktkontakt mit der Schule' },
    ],
    packages: [
      { name: 'One-Pager', price: '฿22,000', eur: '~€560', features: ['Schulinfo','Thai & Englisch','Kontaktformular','LINE-Button'], highlight: false },
      { name: 'Business', price: '฿38,000', eur: '~€970', features: ['Online-Anmeldung','Lehrerprofile','Galerie','SEO'], highlight: true },
      { name: 'Premium', price: '฿58,000', eur: '~€1,480', features: ['Schülerportal','Kalendersystem','Mehrsprachig','Vollst. SEO'], highlight: false },
    ],
  },
}
