export const spaImgs = {
  hero: 'https://images.pexels.com/photos/3997993/pexels-photo-3997993.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  mid:  'https://images.pexels.com/photos/3764568/pexels-photo-3764568.jpeg?auto=compress&cs=tinysrgb&w=800&q=80',
  cta:  'https://images.pexels.com/photos/3865792/pexels-photo-3865792.jpeg?auto=compress&cs=tinysrgb&w=1920&q=80',
  gradient: 'from-emerald-950/80',
}

export const spaContent = {
  th: {
    eyebrow: 'สปา & นวดแผนไทย · ภูเก็ต', h1_main: 'เว็บไซต์สปา & นวด', h1_sub: 'ที่นักท่องเที่ยวหาเจอ',
    hero_desc: 'เว็บไซต์สวยงาม จองออนไลน์ และ SEO นานาชาติ ให้นักท่องเที่ยวหาสปาของคุณเจอใน Google',
    mid_h2: 'นักท่องเที่ยวจองออนไลน์',
    mid_p: 'ภูเก็ตมีสปาหลายพันแห่ง สปาที่พบออนไลน์เต็มตลอด ที่เหลือรอลูกค้าเดินเข้ามา',
    services: [
      { icon: '📅', label: 'จองนัดออนไลน์', sub: 'ลูกค้าจองตรงจากเว็บไซต์' },
      { icon: '💅', label: 'เมนูบริการ', sub: 'บริการและราคาทั้งหมด' },
      { icon: '🌍', label: 'SEO นานาชาติ', sub: 'นักท่องเที่ยวหาเจอใน Google' },
      { icon: '📸', label: 'แกลเลอรีภาพ', sub: 'บรรยากาศ ห้องนวด และผลิตภัณฑ์' },
      { icon: '⭐', label: 'รีวิว', sub: 'รีวิว Google สดบนเว็บไซต์' },
      { icon: '🛁', label: 'แพ็กเกจสปา', sub: 'แพ็กเกจและบัตรของขวัญ' },
      { icon: '🌺', label: 'นวดแผนไทย', sub: 'บริการนวดแผนไทยแบบดั้งเดิม' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'จองตรงผ่าน LINE' },
    ],
    packages: [
      { name: 'หน้าเดียว', price: '฿18,000', eur: '~€460', features: ['เมนูบริการ','ไทย & อังกฤษ','รูปภาพ','จองผ่าน LINE'], highlight: false },
      { name: 'ธุรกิจ', price: '฿32,000', eur: '~€820', features: ['จองออนไลน์','แกลเลอรี','รีวิว','SEO นานาชาติ'], highlight: true },
      { name: 'พรีเมียม', price: '฿50,000', eur: '~€1,280', features: ['ระบบจอง','บัตรของขวัญ','หลายภาษา','แคมเปญ SEO'], highlight: false },
    ],
  },
  en: {
    eyebrow: 'Spa & Massage · Wellness · Phuket', h1_main: 'Website for your spa', h1_sub: 'Found by tourists worldwide',
    hero_desc: 'Beautiful website, online bookings & international SEO. Tourists find your spa on Google.',
    mid_h2: 'Tourists book online',
    mid_p: "Phuket has thousands of spas. The ones found online are always full. The rest wait for walk-ins.",
    services: [
      { icon: '📅', label: 'Online booking', sub: 'Customers book treatments directly' },
      { icon: '💅', label: 'Treatment menu', sub: 'All services & prices overview' },
      { icon: '🌍', label: 'International SEO', sub: 'Tourists find you on Google' },
      { icon: '📸', label: 'Photo gallery', sub: 'Atmosphere, rooms & products' },
      { icon: '⭐', label: 'Reviews', sub: 'Live Google Reviews on your site' },
      { icon: '🛁', label: 'Spa packages', sub: 'Packages & gift vouchers' },
      { icon: '🌺', label: 'Thai massage', sub: 'Traditional Thai massage services' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct booking via LINE' },
    ],
    packages: [
      { name: 'One-Page', price: '฿18,000', eur: '~€460', features: ['Treatment menu','Thai & English','Photos','LINE booking'], highlight: false },
      { name: 'Business', price: '฿32,000', eur: '~€820', features: ['Online booking','Gallery','Reviews','Int. SEO'], highlight: true },
      { name: 'Premium', price: '฿50,000', eur: '~€1,280', features: ['Booking system','Gift vouchers','Multilingual','SEO campaign'], highlight: false },
    ],
  },
  nl: {
    eyebrow: 'Spa & Massage · Wellness · Phuket', h1_main: 'Website voor uw spa', h1_sub: 'Gevonden door toeristen',
    hero_desc: "Prachtige website, online boekingen en internationale SEO. Toeristen vinden uw spa via Google.",
    mid_h2: 'Toeristen boeken online',
    mid_p: "Phuket heeft duizenden spa's. De spa's die online gevonden worden, zijn altijd vol. De rest wacht op walk-ins.",
    services: [
      { icon: '📅', label: 'Online boekingen', sub: 'Klanten boeken behandelingen direct' },
      { icon: '💅', label: 'Behandelmenu', sub: 'Overzicht van alle diensten & prijzen' },
      { icon: '🌍', label: 'Internationale SEO', sub: 'Toeristen vinden u via Google' },
      { icon: '📸', label: 'Fotogallerij', sub: 'Sfeer, behandelkamers & producten' },
      { icon: '⭐', label: 'Reviews', sub: 'Google Reviews live op uw site' },
      { icon: '🛁', label: 'Spa pakketten', sub: 'Pakketten & cadeaubonnen' },
      { icon: '🌺', label: 'Thai massage', sub: 'Traditionele Thaise massages' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direct boeken via LINE' },
    ],
    packages: [
      { name: 'One-Page', price: '฿18,000', eur: '~€460', features: ['Behandelmenu',"Thai & Engels","Foto's",'LINE boeken'], highlight: false },
      { name: 'Business', price: '฿32,000', eur: '~€820', features: ['Online boekingen','Gallerij','Reviews','Int. SEO'], highlight: true },
      { name: 'Premium', price: '฿50,000', eur: '~€1,280', features: ['Boekingssysteem','Cadeaubonnen','Meertalig','SEO campagne'], highlight: false },
    ],
  },
  ru: {
    eyebrow: 'Спа & Массаж · Пхукет', h1_main: 'Сайт для спа-салона', h1_sub: 'Который находят туристы',
    hero_desc: 'Красивый сайт, онлайн-бронирование и международный SEO. Туристы найдут ваш спа в Google.',
    mid_h2: 'Туристы бронируют онлайн',
    mid_p: 'На Пхукете тысячи спа-салонов. Те, которых находят онлайн, всегда заняты. Остальные ждут случайных клиентов.',
    services: [
      { icon: '📅', label: 'Онлайн-запись', sub: 'Клиенты записываются напрямую' },
      { icon: '💅', label: 'Меню услуг', sub: 'Все услуги и цены' },
      { icon: '🌍', label: 'Международный SEO', sub: 'Туристы находят вас в Google' },
      { icon: '📸', label: 'Фотогалерея', sub: 'Атмосфера, кабинеты и продукты' },
      { icon: '⭐', label: 'Отзывы', sub: 'Живые отзывы Google на сайте' },
      { icon: '🛁', label: 'Спа-пакеты', sub: 'Пакеты и подарочные сертификаты' },
      { icon: '🌺', label: 'Тайский массаж', sub: 'Традиционный тайский массаж' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Прямая запись через LINE' },
    ],
    packages: [
      { name: 'Одна страница', price: '฿18,000', eur: '~€460', features: ['Меню услуг','Тайский & Английский','Фото','Запись LINE'], highlight: false },
      { name: 'Бизнес', price: '฿32,000', eur: '~€820', features: ['Онлайн-запись','Галерея','Отзывы','Международный SEO'], highlight: true },
      { name: 'Премиум', price: '฿50,000', eur: '~€1,280', features: ['Система бронирования','Сертификаты','Многоязычный','SEO кампания'], highlight: false },
    ],
  },
  de: {
    eyebrow: 'Spa & Massage · Wellness · Phuket', h1_main: 'Website für Ihr Spa', h1_sub: 'Von Touristen gefunden',
    hero_desc: 'Schöne Website, Online-Buchungen & internationales SEO. Touristen finden Ihr Spa bei Google.',
    mid_h2: 'Touristen buchen online',
    mid_p: 'Phuket hat Tausende von Spas. Die online gefundenen sind immer ausgebucht. Der Rest wartet auf Walk-ins.',
    services: [
      { icon: '📅', label: 'Online-Buchung', sub: 'Kunden buchen Behandlungen direkt' },
      { icon: '💅', label: 'Behandlungsmenü', sub: 'Alle Leistungen & Preise' },
      { icon: '🌍', label: 'Internationales SEO', sub: 'Touristen finden Sie bei Google' },
      { icon: '📸', label: 'Fotogalerie', sub: 'Atmosphäre, Räume & Produkte' },
      { icon: '⭐', label: 'Bewertungen', sub: 'Live Google-Bewertungen' },
      { icon: '🛁', label: 'Spa-Pakete', sub: 'Pakete & Gutscheine' },
      { icon: '🌺', label: 'Thaimassage', sub: 'Traditionelle Thaimassage' },
      { icon: '💬', label: 'LINE & WhatsApp', sub: 'Direktbuchung via LINE' },
    ],
    packages: [
      { name: 'One-Pager', price: '฿18,000', eur: '~€460', features: ['Behandlungsmenü','Thai & Englisch','Fotos','LINE Buchung'], highlight: false },
      { name: 'Business', price: '฿32,000', eur: '~€820', features: ['Online-Buchung','Galerie','Bewertungen','Int. SEO'], highlight: true },
      { name: 'Premium', price: '฿50,000', eur: '~€1,280', features: ['Buchungssystem','Gutscheine','Mehrsprachig','SEO-Kampagne'], highlight: false },
    ],
  },
}
